name: Build Ubuntu

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "MySolution.sln"

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init
        run: chmod +x ./build.sh

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build
        run: ./build.sh --target build

      - name: Run Tests
        run: ./build.sh --exclusive --target tests --skipFunctionalTest false --verbosity verbose
