name: "test-report"
on:
  workflow_run:
    workflows: ["build-ubuntu"]
    branches: ["*"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-20.04
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results-ubuntu
          name: .NET Tests
          path: "*.trx"
          reporter: dotnet-trx
